name: f1-predictor-aws

services:
  minio:
    profiles: ["never"]
  minio-init:
    profiles: ["never"]
  postgres:
    profiles: ["never"]
  mlflow:
    profiles: ["never"]

  app:
    depends_on: !reset
    volumes:
      - ${HOME}/.aws:/home/vscode/.aws:ro
    environment: !override
      AWS_PROFILE: f1-predictor
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      F1_DATABASE_URL: postgresql://f1_predictor:${F1_PREDICTOR_DB_PASSWORD}@${RDS_HOST}:5432/f1_predictor
